services:
  - type: web
    name: notion-webhook-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python notion_webhook.py"
    envVars:
      - key: NOTION_DATABASE_ID
        value: "your-database-id"
      - key: NOTION_TOKEN
        value: "your-secret-integration-token"
