services:
  - type: web
    name: gbpjpy-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: OANDA_ACCOUNT_ID
        value: "your-account-id"
      - key: OANDA_ACCESS_TOKEN
        value: "your-oanda-token"
      - key: NOTION_TOKEN
        value: "your-notion-api-token"
      - key: NOTION_DATABASE_ID
        value: "your-database-id"
